export const ADD_ITEM_TO_LIST = "ADD_ITEM_TO_LIST";
export const REMOVE_ITEM_FROM_LIST = "REMOVE_ITEM_FROM_LIST";
export const COMPLETE_ITEM = "COMPLETE_ITEM";
export const SET_FILTER_TYPE = "SET_FILTER_TYPE";
export const CLEAR_COMPLETED = "CLEAR_COMPLETED";
